# Generated by Django 4.2.5 on 2023-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
