# Generated by Django 4.2.5 on 2023-10-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactusrequest'),
    ]

    operations = [
    ]
