# Generated by Django 4.2.5 on 2023-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20231017_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='send_from',
            field=models.CharField(default='homepage', max_length=255),
        ),
        migrations.AddField(
            model_name='contactusrequest',
            name='send_from',
            field=models.CharField(default='homepage', max_length=255),
        ),
    ]
