# Generated by Django 4.2.5 on 2023-10-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_callbackrequest_send_from_contactusrequest_send_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('needs_description', models.TextField()),
                ('send_from', models.CharField(default='homepage', max_length=255)),
            ],
        ),
    ]
