# Generated by Django 4.2.5 on 2023-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_creatorsrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorsCallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('send_from', models.CharField(default='homepage', max_length=255)),
            ],
        ),
    ]
