# Generated by Django 4.2.5 on 2023-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contactusrequest_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorsIND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('creatorType', models.CharField(max_length=255)),
                ('socialLink', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
